version: '3.8'

services:
  nacos:
    image: nacos/nacos-server:v2.3.0
    container_name: ${COMPOSE_PROJECT_NAME}-nacos
    restart: unless-stopped
    environment:
      MODE: ${NACOS_MODE}
      PREFER_HOST_MODE: hostname
      SPRING_DATASOURCE_PLATFORM: mysql
      MYSQL_SERVICE_HOST: ${COMPOSE_PROJECT_NAME}-mysql
      MYSQL_SERVICE_DB_NAME: ${NACOS_DB_NAME}
      MYSQL_SERVICE_USER: ${MYSQL_USER}
      MYSQL_SERVICE_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_SERVICE_DB_PARAM: characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    ports:
      - "${NACOS_PORT}:8848"
      - "9848:9848"
    volumes:
      - nacos_data:/home/nacos/data
      - nacos_logs:/home/nacos/logs
    networks:
      - scaffolding-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8848/nacos/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  scaffolding-network:
    name: ${NETWORK_NAME}
    external: true

volumes:
  nacos_data:
    name: ${COMPOSE_PROJECT_NAME}-nacos-data
  nacos_logs:
    name: ${COMPOSE_PROJECT_NAME}-nacos-logs