# spring 配置
server:
  port: 28928
  servlet:
    context-path: /
spring:
  application:
    name: ai
  main:
    allow-bean-definition-overriding: true
  ai:
    chat:
      client:
        enabled: false # false的情况下禁止自动装配，就可以创建多个ChatClient了
    # 基于ollama去拉取模型
    ollama:
      base-url: http://localhost:11434
      chat:
        model: deepseek-r1:14b
#     基于openai去拉取模型
    openai:
      base-url: https://chatapi.littlewheat.com
      api-key: sk-YiB76FYEBysWcTUw69FEGVfwqMzf1iKMILvobZg3ALVHFl63
      chat:
        options:
          model: gpt-4o
      embedding:
        options:
          model:
          dimensions:
        base-url:
        api-key:

ai:
  openai:
    grok-3:
      base-url: https://chatapi.littlewheat.com
      api-key: sk-YiB76FYEBysWcTUw69FEGVfwqMzf1iKMILvobZg3ALVHFl63
      model: grok-3
      temperature: 0.7
      embeddingModelName: text-embedding-v3
      embeddingDimensions: 1024
    gpt-4o:
      base-url: https://chatapi.littlewheat.com
      api-key: sk-YiB76FYEBysWcTUw69FEGVfwqMzf1iKMILvobZg3ALVHFl63
      model: gpt-4o
      temperature: 0.5
      embeddingModelName: text-embedding-v3
      embeddingDimensions: 1024

  ollama:
    deepseek:
      base-url: http://localhost:11434
      model: deepseek-r1:14B
      temperature: 0.7
    qwen3:
      base-url: http://localhost:11434
      model: qwen3:14b
      temperature: 0.5
    deepseek-v3_Q4:latest:
      base-url: http://10.244.51.171:8000
      model: deepseek-v3_Q4:latest
      temperature: 0.7
    deepseek-r1:7b:
      base-url: http://10.244.22.55:11434
      model: deepseek-r1:7b
      temperature: 0.9


datasource:
  localhost:
    jdbc-url: jdbc:mysql://localhost:3306/ysx
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    org:
      springframework:
        ai:
          chat:
            client:
              advisor: debug
