# spring 配置
server:
  port: 28920
  servlet:
    context-path: /main
spring:
  application:
    name: server-main
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    ssl: false
    database: 0
    timeout: 6000
    lettuce:
      pool:
        max-active: 16
        max-idle: 60
        min-idle: 60
        max-wait: 6000

# eureka配置
eureka:
  #设置注册方式为ip注册，设置注册地址
  instance:
    instanceId: localhost:28920
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 4 #主动心跳时间间隔
    lease-expiration-duration-in-seconds: 12  #超过该事件eureka没接到心跳会剔除该实例
  client:
    serviceUrl:
      defaultZone: http://localhost:28921/eureka/


#apollo配置
app:
  id: ysx
apollo:
  env: DEV
  cluster: back_end_scaffolding
  meta: http://localhost:8080
#  meta: http://192.168.226.1:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: application,configuration
    eagerLoad:
      enabled: false

##log配置
#logging:
#  level:
#    org.xiaoxingbomei.dao.*.*: debug
#
##分页插件
#pagehelper:
#  auto-runtime-dialect: true

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true