# spring 配置
server:
  port: 28920
  servlet:
    context-path: /main
spring:
  application:
    name: server-main
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
    ssl: false
    database: 0
    timeout: 6000
    lettuce:
      pool:
        max-active: 16
        max-idle: 60
        min-idle: 60
        max-wait: 6000

# eureka配置
eureka:
  #设置注册方式为ip注册，设置注册地址
  instance:
    instanceId: localhost:28920
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 4 #主动心跳时间间隔
    lease-expiration-duration-in-seconds: 12  #超过该事件eureka没接到心跳会剔除该实例
  client:
    serviceUrl:
      defaultZone: http://localhost:28921/eureka/




#apollo配置
app:
  id: ysx
apollo:
  env: DEV
  cluster: back_end_scaffolding
  meta: http://localhost:8080
#  meta: http://192.168.226.1:8080
  autoUpdateInjectedSpringProperties: true
  bootstrap:
    enabled: true
    namespaces: application,configuration
    eagerLoad:
      enabled: false

##log配置
#logging:
#  level:
#    com.dsp.mdb.dao.*.*: debug
#
##分页插件
#pagehelper:
#  auto-runtime-dialect: true
