# tomcat配置
server:
  port: 10001
  servlet:
    context-path: /main

# spring配置
spring:
  application:
    name: main
  main:
    allow-bean-definition-overriding: true
    
  # Redis配置 - 最佳实践版本
  data:
    redis:
      # =================== 基础连接配置 ===================
      # Redis服务器地址
      host: localhost
      # Redis服务器端口
      port: 6379
      # Redis密码（生产环境建议设置密码）
      # password: your_redis_password
      # 数据库索引（0-15，建议不同业务使用不同库）
      database: 0
      # 连接超时时间（建议3-5秒）
      timeout: 3000ms
      
      # =================== Lettuce配置（推荐）===================
      # Lettuce是Spring Boot 3.x默认的Redis客户端
      # 优势：基于Netty的NIO，支持异步、连接复用、高性能
      lettuce:
        pool:
          # 连接池最大连接数（生产环境建议根据并发量调整，一般8-20）
          max-active: 10
          # 连接池最大阻塞等待时间（-1表示无限等待，生产环境建议设置具体值）
          max-wait: 3000ms
          # 连接池中的最大空闲连接（建议与max-active相等或略小）
          max-idle: 8
          # 连接池中的最小空闲连接（建议设置为2-4，保持一定的预热连接）
          min-idle: 2
        # 关闭超时时间（连接闲置多久后关闭）
        shutdown-timeout: 100ms
        
      # =================== 性能优化配置 ===================
      # 客户端名称（便于监控和调试）
      client-name: ${spring.application.name}
      # 客户端类型（lettuce或jedis，Spring Boot 3.x默认lettuce）
      client-type: lettuce

# SpringDoc OpenAPI 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.xiaoxingbomei.controller

# 开启调试模式，查看自动配置报告
#debug: true
#logging:
#  level:
#    org.springframework.boot.autoconfigure: DEBUG
#    org.xiaoxingbomei.config.datasource: DEBUG
  


# 统一多数据源配置示例
multi-datasource:
  datasources:
    # 数据源配置
    local:
      # 数据库连接信息
      url: jdbc:mysql://localhost:3306/ysx
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

      # 连接池配置（可选，有默认值）
      initial-size: 5
      max-active: 20
      min-idle: 5
      max-wait: 60000

      # MyBatis配置
      mapper-locations: classpath*:org/monitorx/dao/local/*.xml
      base-packages: org.monitorx.dao.local
      call-setters-on-nulls: true
