# spring 配置
server:
  port: 10002
  servlet:
    context-path: /
spring:
  application:
    name: auth
  main:
    allow-bean-definition-overriding: true


# 多数据源配置
datasource:
  multiple:
    # 数据源1: 权限数据库 (主数据源)
    ysx:
      url: jdbc:mysql://localhost:3306/ysx_dev?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
      driverClassName: com.mysql.cj.jdbc.Driver
      entityPackages: org.xiaoxingbomei.entity.auth
      repositoryPackages: org.xiaoxingbomei.repository.auth
      primary: true
      # 连接池配置
      maximumPoolSize: 20
      minimumIdle: 5
      connectionTimeout: 30000
      idleTimeout: 600000
      maxLifetime: 1800000


# JPA通用配置
jpa:
  hibernate:
    ddl-auto: update
    naming:
      physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  show-sql: true
  open-in-view: false
  database-platform: org.hibernate.dialect.MySQL8Dialect
  properties:
    hibernate:
      format_sql: true
      use_sql_comments: true
      jdbc:
        batch_size: 50
      order_inserts: true
      order_updates: true


# sa-token 配置
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: satoken
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: 2592000
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# Redis配置
redis:
  host: localhost
  port: 6379
  password:
  database: 1
  timeout: 6000ms
  lettuce:
    pool:
      max-active: 200
      max-wait: -1ms
      max-idle: 20
      min-idle: 0


# SpringDoc OpenAPI 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: org.xiaoxingbomei.controller